### ISSUE TITLE
A critical error has occurred. Please check the Event Viewer for further details.

### ISSUE THREAD

**Issue by abuhmead1987** [DNN-Connect/DNN-Blog#35]
Dears, 

I installed release Blog_06.01.02, and I configured it on my site, showing the list of Posts, Calendar, Tags Cloud and the list of blogs all are on the same page, It woks fine, but after few hours just the following error appears "A critical error has occurred. Please check the Event Viewer for further details",  

TYPE:DotNetNuke.Services.Search.SearchEngineScheduler, DOTNETNUKE
EXCEPTION:Unable to cast object of type 'DotNetNuke.Modules.Blog.Common.ViewSettings' to type 'System.Collections.Generic.Dictionary`2[System.Int32,System.Collections.Hashtable]'.
RESCHEDULED FOR:6/16/2015 10:44:55 AM
SOURCE:STARTED_FROM_TIMER
ACTIVE THREADS:0
FREE THREADS:1
READER TIMEOUTS:0
WRITER TIMEOUTS:0
IN PROGRESS:0
IN QUEUE:5
Server Name: web2

I saw this link http://www.luiscabrera.me/Blog/Post/1107/Exception-in-ViewSettings-get_Settings-DNN-Blog-Module but it doesn't solve the problem
and also this one 
http://www.luiscabrera.me/Blog/Post/1109/Exception-in-ViewSettings-get_Settings-RESOLUTION

Please Help me

**Comment by gigocabrera** [comment]
Did you upgrade from an older version or is this a brand new install?
If I had to guess I would say something went wrong during the installation. I've seen this before and the error is caused by the search scheduled task in DNN. If you disable that task the problem goes away (you can try that as a work around for now).

**Comment by abuhmead1987** [comment]
Thank you for your reply, I deleted the previous installation of this module and I installed 06.01.02, the problem solved, The problem was because of upgrading

**Comment by gigocabrera** [comment]
Glad to hear!
