### ISSUE TITLE
Content Import Failing

### ISSUE THREAD

**Issue by gavcoop123** [DNN-Connect/DNN-Blog#37]
Installed 06.01.02 
I decide to roll back to 6.00.5
exported content out to xml.
uninstalled 06.01.02 
installed 6.00.5
import xml fails. progress circle spins then stops.
uninstalled 6.00.5
reinstalled 06.01.02 
import xml
find folder & File
progress indicator circle spins then stops.
no error, resolves to import screen with files selected and xml displayed.

are there specific settings that need to be enabled for successful import.

XML here:  
https://taconic.box.com/s/bp5siimhf26u9znp1i1rhewaa5n0nrng

**Comment by gigocabrera** [comment]
Is this still an issue?
