### ISSUE TITLE
OG Debugger does not like og:image tags

### ISSUE THREAD

**Issue by mrswoop** [DNN-Connect/DNN-Blog#47]
I ran a blog on 6.1.2 (DNN 7.4.1) through the Facebook debugger and it does not seem to like the image configuration. Attached is a screenshot of the debugger results, or you can run it through yourself: [Blog](http://tough.net/Home/Post/215/Best-Excel-Trick-I-ve-Seen-Lately)

Ultimately it resolved to the right image, but it's the only image on the page so I'm not sure how it might respond in a different situation.

![image](https://cloud.githubusercontent.com/assets/265961/9652825/a22b28bc-51d3-11e5-8600-0b3a7b8e9381.png)

**Comment by donker** [comment]
I'm going to have to park this one for now. It will require a completely new approach to our images (i.e. a new image handler). Since we have to deal with security (not all blog posts are public) we can't just create direct links to images.

**Comment by mrswoop** [comment]
Dropping the tilda did fix this... I am able to get these urls to validate even in Google structured data. Thanks, Peter!

**Comment by donker** [comment]
The url is now wrapped in a ResolveUrl (Blog.ascx.vb line 138)
