### ISSUE TITLE
og:description tag fouled by use of quotation marks

### ISSUE THREAD

**Issue by mrswoop** [DNN-Connect/DNN-Blog#48]
If the blog summary (including one autogenerated from content) contains quotation marks, those are used un-encoded in the rendered og tag, throwing off the page HTML.

**Comment by donker** [comment]
I can't seem to replicate this. Are you on the latest version of the module?

**Comment by donker** [comment]
I get something like this:

<item>
      <title>Test post this time</title>
      <link>http://custom/blogdev/module/test-post-this-time</link>
      <description>&lt;p&gt;Western leaders have criticised Russia for its &amp;quot;destabilising&amp;quot; influence on the crisis in eastern Ukraine, as they opened a Nato summit in Wales.&lt;/p&gt;</description>
      <author>BigManager (manager@bring2mind.biz)</author>
      <blog:author>manager@bring2mind.biz</blog:author>
      <category>Two</category>
      <guid isPermaLink="true">http://custom/blogdev/module/test-post-this-time</guid>
      <pubDate>Tue, 04 Nov 2014 15:07:03 GMT</pubDate>
      <blog:publishedon>2014-11-04 15:07:03Z</blog:publishedon>
    </item>

**Comment by gigocabrera** [comment]
If you add quotation marks to the title of a blog post you end up with something like below. This is a bug.

    <meta property="og:title" content="When "Christmas Presents Strike Back" />

**Comment by donker** [comment]
It is now cleaned through method CleanStringForXmlAttribute
