### ISSUE TITLE
Token for Next/Previous Post

### ISSUE THREAD

**Issue by hismightiness** [DNN-Connect/DNN-Blog#58]
As a blog implementer, it would be nice to have a token that can be added to the post details template that displayed the ability to move from the current post to the next post, or from the current post to the previous post.  This would help provide some stickiness and usability for various forms of blog implementations.

**Comment by donker** [comment]
The approach taken by the module makes this very hard. When a post is displayed in detail, there is no retrieval of the list of which it is a part. So it has no idea what is next or previous.

Instead what you could try is to make a template that switches out the page content div (master to detail) so the context remains the list. This will require a bit of JS wizardry but it is your best bet.
