### ISSUE TITLE
Latest Posts url localization

### ISSUE THREAD

**Issue by fprati** [DNN-Connect/DNN-Blog#59]
The latestPosts template post.html does not work properly with localization. Although the title of the featured post is correct (  <a href="[post:parenturl]">[post:localizedtitle]</a>) the link is not because it leads to the default language blog post. I believe [post:parenturl] fails to use the localized parent blog.
Is there a fix or a better token to be used?

**Comment by gigocabrera** [comment]
@fprati 
1) What version of the blog module are you using? 
2) What template are you using?
3) Is there a URL you can provide so we can take a look?

**Comment by fprati** [comment]
It happens at least with 6.1.1, 6.1.2 and 6.2.0,
It is the latestPosts post.html.
You can clearly see it here: http://www.energolux-gdfsuez.lu/de/startseite

**Comment by gigocabrera** [comment]
On the Module Settings --> Basic Settings section, what is the Module Culture selected?

**Comment by fprati** [comment]
It is French on the French side and German on the German side. I also tried to change from detached to non-detached and tried various other settings, but the result is the same or no posts shown on the DE side.
Btw, it's on dnn 7.3.2.

**Comment by gigocabrera** [comment]
@fprati I was able to replicate your issue on a local install with DNN 7.4.2 and blog 6.2. As a matter of fact, there are other templates that are not working correctly with localization.

**Comment by fprati** [comment]
While waiting it to be fixed, is there a possible workaround, by any chance?

**Comment by cdhd2** [comment]
Was there ever a resolution to this problem? I have the same issue on a site with 4 languages.

**Comment by fprati** [comment]
Still waiting...

**Comment by cdhd2** [comment]
Thanks fprati!

**Comment by donker** [comment]
I've added "language=" to the queystring for permalinks if the post has a set locale. I don't have the capacity to verify if this will solve the problem but I think it could.

**Comment by fprati** [comment]
Hi, what does that mean to us? Can you be more explicit on the change we should make, please?

**Comment by donker** [comment]
It means you should try version 6.4.0 to see if it solves your issue.

**Comment by valadas** [comment]
@fprati I have closes #90 (same issue) because I was not able to reproduce this behaviour. Please open a new issue and include step be step instructions on how to reproduce the problem and I will be glad to try again. Thanks
In the steps to reproduce be as precise as possible, include Dnn version, Module versions, all steps to enable languages, creating the blog page, how you setup the module localization, really detailed information please.
