### ISSUE TITLE
cannot set parent blog 

### ISSUE THREAD

**Issue by pduszkiewicz** [DNN-Connect/DNN-Blog#61]
We have installed DNN Blog on Evoq Content. I am able to do everything except to reference a parent blog from a blog module created on different page. The issue is that the parent blog drop down is not being populated. 

Has anyone encountered this issue?

**Comment by gigocabrera** [comment]
@pduszkiewicz I don't have access to Evoq Content, I'm using the community version but I just tried it on blog 6.2 and it's working fine for me. I added a new Blog module to a new page, selected settings on the Context menu and I was able to reference a parent blog from the dropdown.

**Comment by pduszkiewicz** [comment]
I'm wondering if it's a problem with Evoq Content which is DNN 7.2. I'll have to try downloading the recent code set and compiling it against our libraries to see if that resolves the issue.
