### ISSUE TITLE
Problem when using a TagList Template

### ISSUE THREAD

**Issue by peterdamm** [DNN-Connect/DNN-Blog#64]
This issue has already been reported a while ago over here:
http://www.dnnsoftware.com/forums/threadid/517708/scope/posts/dnn-blog-611-problem-with-tag-list
and here:
http://www.dnn-usergroup.de/Community/Forum/tabid/72/aff/10/afv/topic/aft/14769/Language/en-US/Default.aspx

Now a customer of mine had the same problem. I downloaded the source and implemented a quick fix in Blog.asxc.vb in the case-Statement from line 330 and below. As I'm not into DNN or the Blog Module there is no guarantee that it fixes the problem for the others, too nor that it does not cause any other bugs.

So here is my fix for you to review and maybe include in future versions:

    If callingObject IsNot Nothing AndAlso TypeOf callingObject Is PostInfo Then
        For Each t As TermInfo In CType(callingObject, PostInfo).PostTags
            If BlogContext.ParentModule IsNot Nothing Then
                t.ParentTabID = BlogContext.ParentModule.TabID
            End If
            Replacers.Add(New BlogTokenReplace(Me, BlogContext.Post, t))
         Next
    ElseIf BlogContext.Post IsNot Nothing Then
        For Each t As TermInfo In BlogContext.Post.PostTags
            If BlogContext.ParentModule IsNot Nothing Then
                t.ParentTabID = BlogContext.ParentModule.TabID
            End If
            Replacers.Add(New BlogTokenReplace(Me, BlogContext.Post, t))
        Next
    Else
        For Each t As TermInfo In TermsController.GetTermsByModule(BlogContext.BlogModuleId, BlogContext.Locale).Where(Function(x) x.VocabularyId = 1).ToList
            If BlogContext.ParentModule IsNot Nothing Then
                t.ParentTabID = BlogContext.ParentModule.TabID
            End If
            Replacers.Add(New BlogTokenReplace(Me, Nothing, t))
        Next
    End If
    _usePaging = False

**Comment by grayspace** [comment]
Hi @peterdamm ... Thanks for posting this fix. I'm having the same problem here, and I can't really wait  until it's folded into a future release. Is the fix still working for you? Also, would you mind explaining the process you took to make this modification? Did you paste all the "resources.zip" contents into the DesktopModules/Blog folder, and build from there after making the edit?

**Comment by peterdamm** [comment]
Hi @grayspace,

yes, the fix is still working. I just took the latest version from github, made my changes and build the whole project. Then I replaced the .dll files in the bin folder of the DNN installation.

Hope this helps.

**Comment by TopCat6** [comment]
I, too would like this fixed ASAP, but until that happens I have added this jquery code to the Header section of the module (Module Settings, Advanced Settings) to hide the error message when it appears, so the site doesn't look so bad.
```
<script type="text/javascript">
$(document).ready(function () {
$("div.tagList_list:contains('Error:')").css("display", "none");
})
</script>
```

**Comment by donker** [comment]
I've integrated the code for the next release
