### ISSUE TITLE
Categories and tags not displayed

### ISSUE THREAD

**Issue by sjthompsonengl** [DNN-Connect/DNN-Blog#67]
I'm seeing an issue with 6.2.2 on DNN version 7.3.4 where the categories and tags are not displayed under the "Publishing Details" section.
![categories-and-tags](https://cloud.githubusercontent.com/assets/6450312/12894852/4283a016-ce91-11e5-8de2-ccedc2df9a8a.jpg)

What could cause this?

Thanks,
Steve

**Comment by donker** [comment]
Either: 1. no categories created yet, 2. css conflict causing stuff to hide, or 3. js conflict causing the tree to break. It has to be debugged using Firebug for instance.
