### ISSUE TITLE
Blog 6.2.2 loading up the event viewer with get_item exceptions

### ISSUE THREAD

**Issue by hismightiness** [DNN-Connect/DNN-Blog#69]
I have this running on DNN 7.4.2.

I'm currently seeing error being written to the event log very often.  About 100 times over the past 10 hours alone.  

Anyone else running into this, or know what the cause might be?  I'd be willing to put in a PR if someone could point me in the right direction.

2/18/2016 1:23:51 PMGeneral Exception    AbsoluteURL DefaultDataProvider DotNetNuke.Data.SqlDataProvider DotNetNuke 
AbsoluteURL:
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:f748505e-66c1-433b-b888-1e5f588af61a
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:Sw4jmWcaIHQ6SIgZu2hzPg==
Message:NrComments
StackTrace:
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at DotNetNuke.Modules.Blog.Entities.Posts.PostInfo.Fill(IDataReader dr)
   at DotNetNuke.Common.Utilities.CBO.FillObjectFromReader(Object objObject, IDataReader dr)
InnerMessage:
InnerStackTrace:
Source:System.Data
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: [REMOVED]

**Comment by hismightiness** [comment]
Still an issue.

**Comment by hismightiness** [comment]
This must be unique to my instance since there's not been any activity on this issue.  I was getting sometimes hundreds of this same exception every few minutes.  I don't why it's happening, but if I replace this line below:

`NrComments = Convert.ToInt32(Null.SetNull(dr.Item("NrComments"), NrComments))`

With this, the error goes away.

```
Try
    NrComments = Convert.ToInt32(Null.SetNull(dr.Item("NrComments"), NrComments))
Catch
    NrComments = 0
End Try
```

I'd submit this as a PR, but I'm not running on DNN 8 and am unsure of which brand to participate in.

**Comment by donker** [comment]
I'll move NrComments to the view so it appears in all results
