### ISSUE TITLE
WLW Sync Theme fails

### ISSUE THREAD

**Issue by ergodaveh** [DNN-Connect/DNN-Blog#70]
Using Live Writer 2012 on W10 
DnnBlog 6.01.01 on DNN 7.1.2   

The theme update on WLW2012 fails to complete.
Not sure where do we look for error message(s)?

Cheers,

**Comment by donker** [comment]
You can try to see if you can find something using Fiddler, or you can try the latest version of the module (but you'll need DNN 8)
