### ISSUE TITLE
When adding post not able to add title

### ISSUE THREAD

**Issue by SharePointGuy1** [DNN-Connect/DNN-Blog#73]
After having installed the module, adding an instance to a page, then trying to add a new post, I am unable to add a title. This is what I see and there is no place to add title. 

Anyone have any idea why this might be?

![addblogpost](https://cloud.githubusercontent.com/assets/7844232/13620697/7cf7a7f8-e546-11e5-9fa1-9c085e494146.PNG)
![addblogpost](https://cloud.githubusercontent.com/assets/7844232/13620714/a32f153c-e546-11e5-903d-d1b20d8c997e.PNG)

**Comment by mrswoop** [comment]
This is definitely not a universal problem. Did you try inspecting the page, could it be a CSS issue?

**Comment by giffordwatkins** [comment]
Click below the Title: there should be a field there?

<input name="dnn$ctr1354$PostEdit$txtTitle_txtMain" type="text" id="dnn_ctr1354_PostEdit_txtTitle_txtMain">  

( css should be found here:     http://sitename.com/DesktopModules/Blog/module.css )

**Comment by SharePointGuy1** [comment]
mrswoop and giffordwatkins,

Thanks for the responses. For some reason I was having a problem finding from within Firefox, but once I was able to do so in Edge and Chrome, was able to get it done from Firefox.
