### ISSUE TITLE
Posts Collection does not honor "All Blogs" setting

### ISSUE THREAD

**Issue by mrswoop** [DNN-Connect/DNN-Blog#74]
I have an instance of the LatestPosts module on the blog page. The page hosts one blog module with two blogs on it. The module settings on the LatestPosts module instruct it to display "All" blogs. However, when looking at blog detail, only posts from that blog's collection are shown, posts from the other blog are not shown. 

If I change the module settings to one blog or the other, that setting is honored. But when the setting is "All", the Posts collection defaults to containing only the posts for the blog that is being displayed. It seems you cannot get it to display a list of all the posts in the blog instance (ie. from both of the blogs).

I am using Blog 6.3.0 on DNN 8.0.1

**Comment by donker** [comment]
I can't reproduce this, Scott. I've added a latestPosts module that points to the mother module and it shows all blog posts. Even when I've set the parent module to show only one blog (not sure if that use case is all that important, though).
