### ISSUE TITLE
Installation failed when doing a repair with v6.0.3.

### ISSUE THREAD

**Issue by ErwinCraps** [DNN-Connect/DNN-Blog#75]
When you try to install (repair) version 6.0.3 this will result in a installation failed.  I have the issue on 4 instances.

Error loading files from temporary folder - see below.
StartJob	Starting Installation
Info	Starting Installation - DotNetNuke.Blog
Info	Starting Installation - Script
Info	Begin Sql execution
Info	Creating backup of previous version - Uninstall.SqlDataProvider
Info	Created - Uninstall.SqlDataProvider
Info	Finished Sql execution
Info	Component installed successfully - Script
Info	Starting Installation - Assembly
Info	Assembly already registered - bin\DotNetNuke.Modules.Blog.dll
Info	Creating backup of previous version - bin\DotNetNuke.Modules.Blog.dll
Info	Created - bin\DotNetNuke.Modules.Blog.dll
Info	Assembly already registered - bin\CookComputing.XmlRpcV2.dll
Info	Component installed successfully - Assembly
Info	Starting Installation - Cleanup
Info	Processing Cleanup File - 6.0.0
Failure	ExceptionSchwabenCode.QuickIO.UnmatchedFileSystemEntryTypeException: FileSystemEntryType not matched! at SchwabenCode.QuickIO.QuickIOFile.InternalFileExists(String uncPath) at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFiles(Array arrPaths) at DotNetNuke.Services.Installer.Installers.CleanupInstaller.ProcessCleanupFile()
Failure	Installation Failed - Cleanup
Info	Installation Failed - DotNetNuke.Blog
Info	Deleted temporary install folder
EndJob	Installation Failed

**Comment by mvanlaar** [comment]
This is also with 6.2.2 and dnn 8.0.3 same error.

**Comment by donker** [comment]
Cleanup is the process whereby DNN tries to delete unused files that the module developer has flagged for deletion. The above error means your disk permissions are wrong. Check this:

[http://www.bring2mind.net/Company/News/tabid/155/Post/311/Permissions-permissions-permissions](http://www.bring2mind.net/Company/News/tabid/155/Post/311/Permissions-permissions-permissions)
