### ISSUE TITLE
export blog 

### ISSUE THREAD

**Issue by ortomind** [DNN-Connect/DNN-Blog#76]
Hi,

I get an error when I try to export. Manage > export and the link form Download BlogML File
is not well configured: 

https://www.domain.dot/Blog/ctl/Manage/mid/[object%20Object]
or
http://www.domain.dot/Blog/ctl/Manage/mid/[object%20Object]

I need this along a question: is possible to move the blog to a different instance portal? I know that are some dependencies with the users ...

thank you

**Comment by donker** [comment]
Will be fixed in next release
