### ISSUE TITLE
Blog v6.03 downloaded, can't run .SLN, 3 errors

### ISSUE THREAD

**Issue by raywu1688** [DNN-Connect/DNN-Blog#77]
Hello,

Downloaded the latest (v 6.03), launch the .SLN, got 3 errors (see attached file). Please help resolved. Thank you.

Severity	Code	Description	Project	File	Line	Suppression State
Error	BC30002	Type 'Global.DotNetNuke.Web.UI.WebControls.DnnGrid' is not defined.	DotNetNuke.Modules.Blog	E:\Data\myStuff\Programming\TianetDocs\DNN-BlogMY\DNN-Blog-06.03.00\Manage.ascx.designer.vb	77	Active
Error	BC30002	Type 'Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker' is not defined.	DotNetNuke.Modules.Blog	E:\Data\myStuff\Programming\TianetDocs\DNN-BlogMY\DNN-Blog-06.03.00\PostEdit.ascx.designer.vb	302	Active
Error	BC30002	Type 'Global.DotNetNuke.Web.UI.WebControls.DnnTimePicker' is not defined.	DotNetNuke.Modules.Blog	E:\Data\myStuff\Programming\TianetDocs\DNN-BlogMY\DNN-Blog-06.03.00\PostEdit.ascx.designer.vb	311	Active

![blogerrs](https://cloud.githubusercontent.com/assets/18223824/14866010/51c33b36-0c76-11e6-9351-53415bd16c21.PNG)

**Comment by pblanton** [comment]
I have the same issue...

Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Unknown server tag 'dnn:DNNGrid'.

What is the work-around?

**Comment by donker** [comment]
(a) you must reference the dotnetnuke.web.deprecated library. Check all references.
(b) there is not good syntax checking in ascx files sue to the nature of DNN module projects (unless you wish to load the entire DNN project every time)
