### ISSUE TITLE
Windows Live Writer (WLW) can not connect to Blog

### ISSUE THREAD

**Issue by fujinguyen** [DNN-Connect/DNN-Blog#80]
WLW was able to connect to the blog then sudden stop.  The error message is below.  

"Message:Server returned a fault exception: [0] Please check your URL to make sure you entered the correct URL for your blog. The blog posting URL is available through the blog settings for your blog."

This error came from the Sub GetPortalSettings in the file BlogPost.ashx.   The PortalAliasInfo look up is null.   The fix is use a new method to look up PortalSettings by PortalID. 

Problem code:
PortalSettings = New PortalSettings(TabId, pai)

Fixed code:
PortalSettings = New PortalSettings(PortalId)

Below is temporary fix (removed a few lines not used)

  Private Sub GetPortalSettings()
  Try
   Dim oTabController As TabController = New TabController
   Dim oTabInfo As TabInfo = oTabController.GetTab(TabId, PortalId, False)
   PortalId = oTabInfo.PortalID
   PortalSettings = New PortalSettings(PortalId)
  Catch ex As XmlRpcFaultException
   Throw
  Catch generatedExceptionName As Exception
   Throw New XmlRpcFaultException(0, GetString("PortalLoadError", "Please check your URL to make sure you entered the correct URL for your blog.  The blog posting URL is available through the blog settings for your blog.")) 
  End Try
 End Sub

**Comment by donker** [comment]
Integrated in next release
