### ISSUE TITLE
Search by term is not working

### ISSUE THREAD

**Issue by ufoloko** [DNN-Connect/DNN-Blog#81]
I have a list of posts and Im showing terms used for each post with link.

When I make click on link post are not being filtered just for that term.

URL Contains /Blog/Term/14/enviromental

Please help

**Comment by donker** [comment]
I cannot reproduce any error in this part. Make sure you're on the latest version.

**Comment by ufoloko** [comment]
I have tryied installing last version 6.3 in another site but still have the problem.

Additionally I have downloaded the source code and tested in another site and works, but I dont know how to compile into installer to install from source.

Can you help me with that ?

**Comment by Swimburger** [comment]
I believe I'm running into the same issue. After clicking on the term, the module says "3 post(s) found" but return 18 posts including the 3 relevant.

DNN 09.02.00 (366)
Blog module v6.4.1
